language: node_js
node_js:
    - "node"
cache:
    directories:
        - node_modules
script:
    - yarn test
    - yarn build
notifications:
    email:
        on_success: never # default: change
        on_failure: always # default: always
deploy:
    on:
        branch:
            - master
    provider: firebase
    token:
        secure: Dy2uVcLvDQB+DTc+/5h5JxtlBZuLm5FXabkMmUVIZBStzzNcH9VCczmeLY4ULNcvZW/IemSP8RrPJ0iahgLcccsJsrC/K7Jz1cTZvCZW/TgNhNsET1oYWGpqWxiK1S3pwKWmm6TVJbm/nmfRnX73KgXmRKtU4P2epJImKOg0GEGQZP4htR7pzDOHhBLhc3NH6/V7hbvm+hS4SaciAJHNyPBhidWHRL6DLA7LpxJplzuhK5mgNOu64ZhL3AZ1JSpxMwbOMU2xNgLV8aESWEmbLDjoAX5U4JCLZd6oHoYpAKO2Kd5pSpjPSxpBZc1ohxYiPV8fRPl8niQgHAdcouH4KfT0gkxJA6GpgX8GVk2asV5r/3kd2aU5P6opariKNJdtj92AzoKJqEGjj7u5S3G5l+DjariIp+9kvs+9IHeBpLC4s+6XVJBADiFSUhWrodgecB0ueZmFzyRhl/vR0bngpfWNTT993U8QfegnJtFVG2ncahjch64EiTwO2UKxI9uq259RyyY+5pWVv+yApM6M95nmCM4T9RleCp/S5v/j55wx46JJ1WGyP2Z2v0StzoUgAEqCRTYjd9tF5mq7A+qdfF5G3hDB67hwc0jHu0YSklh0IFaxoLkzVd9noc0LghcEkhRr1aqhkF/tpvQvdvDh3F1WU9UvvNKM+848xoukQnc=
